FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD new_project.jar /opt/new_project/
EXPOSE 8080
WORKDIR /opt/new_project/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "new_project.jar"]
